### ISSUE TITLE
Natural gas changing to CO2 in natural gas generator

### ISSUE THREAD

**Issue by justin-lafayette** [Nightinggale/ONI-mods#5]
Started noticing recently my natural gas generators becoming damaged. Each time is from a wrong element type. Finally caught the issue, but it looks like the element is changing inside the input port of the generators.

Not sure if it is an issue with the game or the mod, but I had not seen it before enabling the mod a few days ago.

Also, I found the output log here: %appdata%\..\locallow\klei\Oxygen Not Included

[oni-issue.zip](https://github.com/Nightinggale/ONI-mods/files/3470135/oni-issue.zip)

Video:
(I used jing so its a .swf file and its choppy...)

https://drive.google.com/open?id=1xfdTWJpIDyLgZOe5xEG4wl-OFpvURkr6

**Comment by justin-lafayette** [comment]
Also, just checked to make sure I am up to date with the master branch and I am.

**Comment by justin-lafayette** [comment]
Just checked it again and watching small bits of natural gas go in. I am going to save up the gas and see if it breaks with the larger bits.

**Comment by jamesbascle** [comment]
If you have two Natural Gas Generators in a line, with the natural gas passing through one and reaching the other, you can see the carbon dioxide move from the first to the second and vice versa. When you do it with the line above the input and dropping it down into the input, the CO2 doesn't come out, but it will still do the damage.

So yeah, carbon dioxide is coming OUT of the natural gas INPUT, certainly.

**Comment by Truinto** [comment]
That video is indeed choppy. Anyway, could you please share a list with all mods you have installed?
What OS you are on? Linux, Mac, Windows?

**Comment by justin-lafayette** [comment]
Yeah not quite sure why but the capture software is free lol.

The only mods I have installed are from ONI-mods. I cloned the repo and put a copy of the mods into the directory as the instructions state.

OS is Windows 10 Pro Build 17134.

The issue is not entirely reliable to reproduce unfortunately. I put the item that combines all the small bits into a large block before allowing it through and changed the pipe layout to not have it run directly through the input before going to the other generators. The issue sometimes happens still with the large blocks, but, again, not reliably.

**Comment by justin-lafayette** [comment]
@Nightinggale you are a magician!

**Comment by jamesbascle** [comment]
Thanks so much @Nightinggale .  Now I won't have to throw my latest map away!

**Comment by jamesbascle** [comment]
Unfortunately I'm still seeing the issue on the latest version with the Natural Gas gens.

**Comment by jamesbascle** [comment]
https://i.imgur.com/XjD7VzJ.png See this screenshot for what it looks like in game.  I have a pure supply of natural gas that feeds the machines, but the CO2 still spontaneously appears in the gas pipe.

**Comment by jamesbascle** [comment]
These are the mods I'm currently using:
Piped output
Blueprints
Pipe Pressure Valve
Ranching Sensors
Plan Buildings Without Materials
Wounded Go To Med Bed
Wireless Automation
Always 3 Interests
Bigger Building Menu
Geyser Calculated Average Output Tooltip
Half Door
Happy Digging: Dwarf Edition
Longer Bridges

**Comment by Nightinggale** [comment]
Are you using the GitHub or Steam version of the mod? I suspect this could be a case of Steam once again not updating mods correctly.

**Comment by jamesbascle** [comment]
I'm using steam.  I will try the one off here.

**Comment by jamesbascle** [comment]
That worked.  Thanks again.
